# Generated by Django 4.2.5 on 2023-09-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time',
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-01-23'),
            preserve_default=False,
        ),
    ]
